### ISSUE TITLE
can't modify line 2

### ISSUE THREAD

**Issue by jAvEE-fr** [rutgerkok/BlockLocker#126]
hello
paper 1.18.1 latest
my admin with bypass and/or op cant change line 2, so cant change owner of the private...

**Comment by rutgerkok** [comment]
Should now be fixed, thanks.

If you want to help testing this, dev builds are available at https://ci.codemc.io/job/rutgerkok/job/BlockLocker/

**Comment by jAvEE-fr** [comment]
i'm sorry, still an issue.

[https://ibb.co/TRfbvW6](url) for an image
